/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        md: "2rem",
        lg: "4rem",
      },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      colors: {
        "on-error": "#450900",
        "secondary-fixed-dim": "#c0bdff",
        "on-secondary-fixed-variant": "#3e32d5",
        "on-secondary-container": "#cecbff",
        "secondary-container": "#3323cc",
        "secondary-dim": "#645efb",
        "surface-variant": "#262626",
        "on-primary-container": "#223600",
        "primary-fixed": "#b8fd4b",
        "primary-fixed-dim": "#aaee3d",
        "surface-container-high": "#201f1f",
        "on-secondary": "#120076",
        "surface-container-low": "#131313",
        "outline": "#777575",
        "surface-container-highest": "#262626",
        "on-surface": "#ffffff",
        "inverse-surface": "#fcf8f8",
        "background": "#0e0e0e",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed": "#a6a9ff",
        "on-primary": "#3d5e00",
        "secondary": "#9492ff",
        "surface-bright": "#2c2c2c",
        "tertiary-container": "#7073ff",
        "on-background": "#ffffff",
        "on-tertiary-fixed-variant": "#1e18b2",
        "outline-variant": "#494847",
        "on-error-container": "#ffd2c8",
        "primary-container": "#83c300",
        "on-secondary-fixed": "#2000b0",
        "on-tertiary-container": "#000000",
        "secondary-fixed": "#cfcdff",
        "surface-tint": "#b8fd4b",
        "surface": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "tertiary-fixed-dim": "#9699ff",
        "error": "#ff7351",
        "error-container": "#b92902",
        "on-primary-fixed": "#304a00",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#456900",
        "primary": "#b8fd4b",
        "on-primary-fixed-variant": "#456900",
        "tertiary-dim": "#6063ee",
        "surface-container": "#1a1919",
        "on-tertiary-fixed": "#050061",
        "primary-dim": "#aaee3d",
        "error-dim": "#d53d18",
        "on-tertiary": "#080079",
        "inverse-on-surface": "#565554",
        "tertiary": "#9093ff"
      }
    },
    screens: {
      sm: "375px",
      md: "768px",
      lg: "1200px",
    },
  },
  plugins: [],
}
